apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: ws-test
    type: poc-module
  name: ws-test
  namespace: poc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: ws-test
      type: poc-module
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: ws-test
        type: poc-module
    spec:
      containers:
      - image: emreodabas/ws-test:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 180
          successThreshold: 1
          timeoutSeconds: 30
        name: ws-test
        ports:
        - containerPort: 8085
          protocol: TCP
        lifecycle:
          preStop:
            httpGet:
              path: /api/shutdown
              port: 8085
              scheme: HTTP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: ws-test
  name: ws-test
  namespace: poc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    name: ws-test
  sessionAffinity: None
  type: NodePort
